version: "3.7"
services:
  booble-maps:
    build: ./boogle-maps
    ports:
      - "9191:9191"
    volumes:
      - type: "volume"
        source: maps
        target: /app
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    volumes:
      - type: "volume"
        source: eurekaV
        target: /app
  pricing-service:
    build: ./pricing-service
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    volumes:
      - type: "volume"
        source: pricing
        target: /app
volumes:
  maps:
  eurekaV:
  pricing: