version: "3.7"
services:
  booble-maps:
    build: ./boogle-maps
    ports:
      - "9191:9191"
    depends_on:
      - eureka
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
  pricing-service:
    build: ./pricing-service
    depends_on:
      - eureka
    ports:
      - "8082:8082"
  vehicles-api:
    build: ./vehicles-api
    depends_on:
      - eureka
    ports:
      - "8080:8080"