version: "3.7"
services:
  booble-maps:
    build: ./boogle-maps
    ports:
      - "9191:9191"
    depends_on:
      - eureka
    environment:
      - EUREKA_URI=http://eureka:8761/eureka/
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
  pricing-service:
    build: ./pricing-service
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka/
  vehicles-api:
    build: ./vehicles-api
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka/
      - PRICING_URI=http://pricing-service:8082
      - MAPS_URI=http://boogle-maps:9191